name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * 0" # gera toda semana (domingo, meia-noite)
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: sereno766
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg

      - name: Commit & push the generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Generated snake animation ğŸ"
          add: "output/*.svg"
          push: true
